# These settings must match:
# - Port numbers specified in the ABB robot controller's system configurations for EGM communication.
egm:
  channel_1:
    port_number: 6511

# These settings must match:
# - Joint names extracted from the ABB robot controller.
#
# Please see http://wiki.ros.org/joint_limits_interface for more details about joint limits.
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.618
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.7925
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.967
  joint_4:
    has_velocity_limits: true
    max_velocity: 5.585
  joint_5:
    has_velocity_limits: true
    max_velocity: 6.9813
  joint_6:
    has_velocity_limits: true
    max_velocity: 7.854
